/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as ReadingGroupRouteImport } from './routes/reading-group'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as AdminEditorsRouteImport } from './routes/admin/editors'
import { Route as ArticleArticleIdRouteImport } from './routes/article/$articleId'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ColumnSlugRouteImport } from './routes/column/$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingGroupRoute = ReadingGroupRouteImport.update({
  id: '/reading-group',
  path: '/reading-group',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorsRoute = AdminEditorsRouteImport.update({
  id: '/admin/editors',
  path: '/admin/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnSlugRoute = ColumnSlugRouteImport.update({
  id: '/column/$slug',
  path: '/column/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/magazine': typeof MagazineRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/magazine': typeof MagazineRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/magazine': typeof MagazineRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/magazine'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/admin/editors'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/profile/$username'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/magazine'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/admin/editors'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/profile/$username'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/magazine'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/admin/editors'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/profile/$username'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MagazineRoute: typeof MagazineRoute
  ReadingGroupRoute: typeof ReadingGroupRoute
  SearchRoute: typeof SearchRoute
  SubmissionsRoute: typeof SubmissionsRoute
  AdminEditorsRoute: typeof AdminEditorsRoute
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ColumnSlugRoute: typeof ColumnSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-group': {
      id: '/reading-group'
      path: '/reading-group'
      fullPath: '/reading-group'
      preLoaderRoute: typeof ReadingGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editors': {
      id: '/admin/editors'
      path: '/admin/editors'
      fullPath: '/admin/editors'
      preLoaderRoute: typeof AdminEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/$slug': {
      id: '/column/$slug'
      path: '/column/$slug'
      fullPath: '/column/$slug'
      preLoaderRoute: typeof ColumnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MagazineRoute: MagazineRoute,
  ReadingGroupRoute: ReadingGroupRoute,
  SearchRoute: SearchRoute,
  SubmissionsRoute: SubmissionsRoute,
  AdminEditorsRoute: AdminEditorsRoute,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ColumnSlugRoute: ColumnSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
