/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReadingGroupRouteImport } from './routes/reading-group'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEditorsRouteImport } from './routes/admin/editors'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as ArticleArticleIdRouteImport } from './routes/article/$articleId'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ColumnSlugRouteImport } from './routes/column/$slug'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as EditorArticleIdRouteImport } from './routes/editor/$articleId'
import { Route as EditorNewRouteImport } from './routes/editor/new'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingGroupRoute = ReadingGroupRouteImport.update({
  id: '/reading-group',
  path: '/reading-group',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorsRoute = AdminEditorsRouteImport.update({
  id: '/admin/editors',
  path: '/admin/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnSlugRoute = ColumnSlugRouteImport.update({
  id: '/column/$slug',
  path: '/column/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorArticleIdRoute = EditorArticleIdRouteImport.update({
  id: '/editor/$articleId',
  path: '/editor/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/writings': typeof WritingsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/editor/$articleId': typeof EditorArticleIdRoute
  '/editor/new': typeof EditorNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/writings': typeof WritingsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/editor/$articleId': typeof EditorArticleIdRoute
  '/editor/new': typeof EditorNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/editor': typeof EditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/reading-group': typeof ReadingGroupRoute
  '/search': typeof SearchRoute
  '/submissions': typeof SubmissionsRoute
  '/writings': typeof WritingsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/editor/$articleId': typeof EditorArticleIdRoute
  '/editor/new': typeof EditorNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/writings'
    | '/admin/editors'
    | '/admin/inbox'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/editor/$articleId'
    | '/editor/new'
    | '/profile/$username'
    | '/admin/'
    | '/articles/'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/writings'
    | '/admin/editors'
    | '/admin/inbox'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/editor/$articleId'
    | '/editor/new'
    | '/profile/$username'
    | '/admin'
    | '/articles'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/reading-group'
    | '/search'
    | '/submissions'
    | '/writings'
    | '/admin/editors'
    | '/admin/inbox'
    | '/article/$articleId'
    | '/articles/$slug'
    | '/column/$slug'
    | '/editor/$articleId'
    | '/editor/new'
    | '/profile/$username'
    | '/admin/'
    | '/articles/'
    | '/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ReadingGroupRoute: typeof ReadingGroupRoute
  SearchRoute: typeof SearchRoute
  SubmissionsRoute: typeof SubmissionsRoute
  WritingsRoute: typeof WritingsRoute
  AdminEditorsRoute: typeof AdminEditorsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ColumnSlugRoute: typeof ColumnSlugRoute
  EditorArticleIdRoute: typeof EditorArticleIdRoute
  EditorNewRoute: typeof EditorNewRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-group': {
      id: '/reading-group'
      path: '/reading-group'
      fullPath: '/reading-group'
      preLoaderRoute: typeof ReadingGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editors': {
      id: '/admin/editors'
      path: '/admin/editors'
      fullPath: '/admin/editors'
      preLoaderRoute: typeof AdminEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/$slug': {
      id: '/column/$slug'
      path: '/column/$slug'
      fullPath: '/column/$slug'
      preLoaderRoute: typeof ColumnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$articleId': {
      id: '/editor/$articleId'
      path: '/editor/$articleId'
      fullPath: '/editor/$articleId'
      preLoaderRoute: typeof EditorArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ReadingGroupRoute: ReadingGroupRoute,
  SearchRoute: SearchRoute,
  SubmissionsRoute: SubmissionsRoute,
  WritingsRoute: WritingsRoute,
  AdminEditorsRoute: AdminEditorsRoute,
  AdminInboxRoute: AdminInboxRoute,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ColumnSlugRoute: ColumnSlugRoute,
  EditorArticleIdRoute: EditorArticleIdRoute,
  EditorNewRoute: EditorNewRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
